[package]
name = "obServer"
version.workspace = true
edition.workspace = true

[dependencies]
var-io.workspace = true
obServer-proxy.workspace = true

[workspace]
resolver = "3"
members = ["crates/*"]
default-members = [".", "crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
var-io = { path = "crates/var-io", version = "0.1.0" }
obServer-proxy = { path = "crates/obServer-proxy", version = "0.1.0" }
